apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
      # These containers are run during pod initialization
      initContainers:
        - name: install
          image: bitnami/git
          command: ["git"]
          args:
            [
              "clone",
              "https://github.com/ps-interactive/lab_aws_access-amazon-eks-cluster-with-api-gateway.git",
              "/var/lib/data/",
            ]
          volumeMounts:
            - name: workdir
              mountPath: "/var/lib/data"
      dnsPolicy: Default
      volumes:
        - name: workdir
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: books-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: book
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
